### ISSUE TITLE
Tetris AI koristeći GA

### ISSUE THREAD

**Issue by iAmNikola** [ftn-ai-lab/ori-2022-siit#26]
### Članovi tima
Nikola Damjanović, SW 71/2019, 5. grupa
### Asistent
Milica Škipina
### Problem koji se rešava
Implementacija agenta, zasnovanog na [genetskom algoritmu](https://en.wikipedia.org/wiki/Genetic_algorithm), koji igra partiju [Tetrisa](https://en.wikipedia.org/wiki/Tetris) po zvaničnim [pravilima Tetrisa](https://tetris.wiki/Tetris_Guideline). Cilj agenta je ostvarivanje što većeg rezultata. Za GUI reprezentaciju koristiće se [ova](https://github.com/injekim/PYTRIS) Python implementacija Tetrisa.
### Algoritam
Genetski algoritam.
### Metrika za merenje performansi
Rezultat koji bot ostvaruje u odnosu na ljudskog igrača.
### Validacija rešenja
Validacija putem dokazivanja konvergencije genetskog algoritma.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by iAmNikola** [comment]
https://github.com/iAmNikola/algotetris
